// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJz7wvT7W9RnCh21DOsMRGO16Z-GIS5_s',
    appId: '1:883145748228:web:b221689d15971449a36a51',
    messagingSenderId: '883145748228',
    projectId: 'reddit-clone-94697',
    authDomain: 'reddit-clone-94697.firebaseapp.com',
    storageBucket: 'reddit-clone-94697.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7oY8vxkGD9XrX2k45IbS7G82P8Dd5yz8',
    appId: '1:883145748228:android:faa7f82af758e52da36a51',
    messagingSenderId: '883145748228',
    projectId: 'reddit-clone-94697',
    storageBucket: 'reddit-clone-94697.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo61IPkUfDvHCwcuAjJFk03Nk7K8lIgMA',
    appId: '1:883145748228:ios:561e3c6c6f09e8c8a36a51',
    messagingSenderId: '883145748228',
    projectId: 'reddit-clone-94697',
    storageBucket: 'reddit-clone-94697.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo61IPkUfDvHCwcuAjJFk03Nk7K8lIgMA',
    appId: '1:883145748228:ios:e12c1e5015bfa5caa36a51',
    messagingSenderId: '883145748228',
    projectId: 'reddit-clone-94697',
    storageBucket: 'reddit-clone-94697.appspot.com',
    iosBundleId: 'com.example.redditClone.RunnerTests',
  );
}
